docker-compose.yaml, docs/code_push/_category_.json, docs/code_push/build.md, docs/code_push/initialize.md, docs/code_push/patch.md, docs/code_push/release.md, docs/code_push/run.md, docs/getting_started/_category_.json, docs/getting_started/install.md, docs/getting_started/log_in.md, docs/getting_started/sign_up.md, docs/getting_started/upgrade.md, docs/index.md
**READY**
- docs: add getting started and code push sections
=> docs: add getting started and code push sections

docs/faq.md
I did some small updates to the FAQs as I moved them.  I did not make any attempt to sort these by frequency.
=> docs: Move the rest of FAQ.md to docs.shorebird.dev

docs/code_push/release.md
Adds the same note about the `--` behavior to `shorebird release` docs that exists in `shorebird build` and `shorebird run`.
Fixes https://github.com/shorebirdtech/shorebird/issues/421
=> docs: add note about '--' behavior to `shorebird release` docs

.github/PULL_REQUEST_TEMPLATE.md
This seems redundant in a docs repository.
=> chore: remove change type from PR template

docs/architecture.md, docs/concepts.md, docs/faq.md, docs/status.md, docs/uninstall.md
Add Concepts page to explain a subset of Shorebird code push terminology.
=> Add Concepts page

docs/faq.md, docusaurus.config.js
Use our vanity url everywhere instead of a direct invite link.
=> chore: use our discord vanity url everywhere

docs/status.md
Also no longer implores customers to break things.
=> Update status page to remove collaborators from 'what does't work yet'

docs/code_push/initialize.md
**READY**
Updates init to mention that `shorebird init` will add the internet permission to the android manifest if it doesn't already exist, and updates the init output to reflect changes since the doc was last updated.
=> update init docs with fresh cli output and note about new init behavior

docs/code_push/initialize.md, docs/code_push/release.mdx
This will need to be updated once we figure out the naming of `ios-preview` vs `shorebird preview`. For now, I used the ios-preview command name but referred to it as "alpha" in the docs.
=> Add ios-preview to release page

docs/guides/code_push_add_to_app.md, docs/guides/code_push_release_app_store.md, docs/guides/code_push_release_play_store.md, docs/guides/multiple_deployment_tracks.md
**READY**
Adds a guide demonstrating how to release a Shorebird app to the Apple App Store.
=> Add iOS releasing guide

docs/ci/github.md
**READY**
- docs(ci): adjust GitHub patch workflow to reflect latest API
=> docs(ci): adjust GitHub patch workflow to reflect latest API

docs/troubleshooting.md
**READY**
Describes how to get around Windows' file length limit when using git.
=> Add troubleshooting note about shorebird failing to install on Windows

docs/troubleshooting.md
**READY**
Due to a [bug](https://github.com/dart-lang/args/issues/252) in the args package, `--` needs to be escaped on Windows to work properly.
=> Add instructions about escaping -- on Windows

docs/ci/codemagic.mdx, docs/ci/github.md
**READY**
Removes the use of `--force`
As per [CodeMagic](https://docs.codemagic.io/yaml-basic-configuration/environment-variables/) and [GitHub](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) docs, CodeMagic will always set the `CI` and `CONTINUOUS_INTEGRATION` variables to true and GitHub will always set `GITHUB_ACTIONS` to true, so no additional setup is required once https://github.com/shorebirdtech/shorebird/pull/1099 lands.
Part of https://github.com/shorebirdtech/shorebird/issues/1097
=> Add notes about CONTINUOUS_INTEGRATION env variable

docs/faq.md
Previously the markdown quotes were bleeding across the PlayStore/AppStore sections.
This fixes that.
=> fix: Fix markdown quotes in App Store section

docs/flutter-version.md
update Flutter version matrix for 3.10.7, 3.13.0, 3.13.1
3.13.1 will be released shortly.
=> docs: update Flutter version matrix for 3.10.7, 3.13.0, 3.13.1

docs/troubleshooting.md
**READY**
Adds a troubleshooting note about automatically incrementing build numbers and the export options plist `manageAppVersionAndBuildNumber` property.
=> Add troubleshooting entry for iOS build numbers

docs/code_push/release.mdx, docs/guides/release/android.md, docs/guides/release/ios.md
**READY**
The `shorebird releases list` command has been deprecated in favor of console.shorebird.dev. This change updates the docs to reflect that.
=> Replace references to releases list command with console links

docs/guides/release/ios.md
**READY**
Because unsigned builds (those generated with `shorebird release ios-alpha --no-codesign`) don't generate an ipa and can't use the Transporter app as an upload method, update the docs to use Xcode instead, which works with both signed and unsigned artifacts.
=> Update iOS releasing guide to use Xcode instead of Transporter

docs/flutter-version.md
Also inverted the feature matrix to make it easier to edit.
Also linked to the "older versions" bug rather than directing customers to file a new bug.
=> doc: clarify that we do not back-port features

docs/teams.md
We sometimes leak the words "Admin" and "Developer" in our error messages, but we never documented what they mean.
=> doc: document Admin and Developer permissions

docs/code_push/patch.mdx
We had a customer who thought they only worked on `release` so adding a note to patch too.
=> doc: explain how to pass args to flutter build from patch

docs/code_push/preview.md
**READY**
Adds tip callout to `code_push/preview` informing the user what is required to use `shorebird preview` and suggesting previewing CI/CD-created releases.
=> Add note about how preview can be used

docs/code_push/_category_.json, docs/flutter-version.md, docs/guides/_category_.json, docs/overview.md, docs/teams.md
Adds an overview page explaining what code push is and how code push works at a high level
=> Add overview page to explain code push at a high level

docs/status.md
Clean up the status page and describe the current state of our iOS project
=> doc: update iOS status

docs/faq.md
**READY**
- docs(faq): using shorebird for all dart changes
=> docs(faq): using shorebird for all dart changes

docs/concepts.md, docs/faq.md, docs/update-strategies.md
Moves some FAQs to the Concepts page for better visibility and to declutter the FAQs page.
=> Move some FAQs to Concepts

docs/code_push/release.mdx
READY
Fixes a typo in the first line of the 'Side-loading and MDM' section's description
=> docs: fix typo in side-loading section

docs/ci/github.md, docs/flutter-version.md
Removes references to removed `flutter-version` options
=> Update docs re: flutter-version removal

docs/troubleshooting.md
Adds reference to `shorebird preview` in the "I created a patch, but it's not showing up in my app" troubleshooting section, and recommends its use.
=> Reference shorebird preview in troubleshooting

docs/status.md
We don't have great data on how many apps are in the stores with
Shorebird. We do know that we have about 1000 monthly active
developers, and several thousand 3mo active developers, so guessing
there are around 1000 apps in the stores.  It's certainly well into the
hundreds.
Also tweaked the wording and ordering a little.
=> docs: tweek our linker status docs a little.

docs/guides/crash-reporting.md, docs/status.md
Bryan added links to the console to download artifacts which makes this page much simpler.
=> docs: update crash reporting to include console instructions

docs/code_push/patch.mdx
**READY**
Small docs improvement, in the example output for a the patch docs section, the subcommand (if it were an android or iOS patch) was missing.
=> docs: Missing subcommand on patch example output

docs/ci/github.md, docs/code_push/patch.mdx, docs/code_push/release.mdx, docs/flutter-version.md, docs/guides/code_push_quickstart.mdx, docs/guides/flavors/android.md, docs/guides/flavors/ios.md, docs/guides/release/ios.md
A bunch of updates to reflect latest versions of our github actions, removal of references to the deprecated `releases delete` command, and slight reorganization of the releases page in our guide.
=> Update docs for accuracy and to reflect impending 1.0

docs/ci/_ci_authentication.md, docs/ci/codemagic.mdx, docs/ci/github.mdx, docs/faq.md
**READY**
This PR extracts the part of the docs that explain how to obtain a CI token in its own reusable file. Which then is used on both the github and codemagic guides. Removing the duplicated docs between both files.
This will make this section of the docs easier to scale as we add more content.
After this, I plan on adding to the `_ci_authentication.md` file about how the token can also be acquired from the console.
=> feat: Don't repeat CI authentication docs

docs/ci/_ci_authentication.md
**READY**
Adds a quick explanation in the CI authentication section about getting the CI token from the web console.
Before this is merged, we need to push a deploy of the console so the feature is available.
=> docs: Adding explanation on docs about getting the ci token on the console

docs/ci/github.mdx
**READY**
In the CI docs section the usage of the `shorebird-release` action was missing the required argument `platform`. This PR addresses that.
=> fix: Action shorebird-release usage

docs/code_push/release.mdx
**READY**
Adds a brief section in the release command docs to mention about the `flutter-version` flag.
=> docs: Adding section on release docs about the flutter version flag

docs/status.md
**READY**
Removing the known issues listing in the low ios linking percentage since that was solved in  `1.0.5`
=> docs: Removing know issues for ios link on status page

src/content/docs/architecture.mdx
**READY**
Fixed a typo in the documentation file **src/content/docs/architecture.mdx** :
The word "an" was incorrectly used instead of "and" in the phrase "build and release a different binary."
=> fix: fixed typo in architecture section

src/content/docs/ci/codemagic.mdx, src/content/docs/ci/github.mdx, src/content/docs/code-push/initialize.mdx, src/content/docs/code-push/patch.mdx, src/content/docs/code-push/release.mdx, src/content/docs/flutter-version.mdx, src/content/docs/guides/code-push-quickstart.mdx, src/content/docs/guides/flavors/android.mdx, src/content/docs/guides/flavors/ios.mdx, src/content/docs/guides/hybrid-apps/ios.mdx, src/content/docs/guides/staging-patches.mdx, src/content/docs/index.mdx, src/content/docs/status.mdx, src/content/docs/troubleshooting.mdx
Replaces instances of the unsupported `:::info` with the supported `:::note`.
See https://starlight.astro.build/guides/authoring-content/#asides for a list of supported asides/callouts/admonitions.
=> Replace :::info with :::note

src/content/docs/ci/codemagic.mdx, src/content/docs/ci/github.mdx, src/content/docs/code-push/initialize.mdx, src/content/docs/code-push/patch.mdx, src/content/docs/code-push/release.mdx, src/content/docs/flutter-version.mdx, src/content/docs/guides/code-push-quickstart.mdx, src/content/docs/guides/flavors/android.mdx, src/content/docs/guides/flavors/ios.mdx, src/content/docs/guides/hybrid-apps/ios.mdx, src/content/docs/guides/staging-patches.mdx, src/content/docs/index.mdx, src/content/docs/status.mdx, src/content/docs/troubleshooting.mdx
Updates the "why am I seeing a native change warning" troubleshooting entry to mention the cause of https://github.com/shorebirdtech/shorebird/issues/2270.
=> Add native changes troubleshooting for version mismatches

src/content/docs/faq.mdx
**READY**
Felt the description on the `https://storage.googleapis.com/` url on the section `Can I use in my country?` section of the FAQ was missing the updater part.
=> docs: improve descriptions of the shorebird's url in the "can I use in my country faq"

astro.config.mjs, src/content/docs/guides/crash-reporting/sentry.mdx
**READY**
Adds a guide explaining how to include patch numbers in Sentry error reports. 
Addresses the Sentry part of https://github.com/shorebirdtech/shorebird/issues/2258. I suspect the Crashlytics guide will be very similar.
=> Add sentry integration guide

src/content/docs/guides/crash-reporting/crashlytics.mdx
Adds Crashlytics guide.
Fixes https://github.com/shorebirdtech/shorebird/issues/2258
=> Add WIP Crashlytics guide

src/content/docs/troubleshooting.mdx
Adds advice to check in pubspec.lock in the native changes troubleshooting section.
=> Add "check in pubspec.lock" advice to troubleshooting

src/content/docs/troubleshooting.mdx
**READY**
- docs(troubleshooting): fix copy for native and asset changes
=> docs(troubleshooting): fix copy for native and asset changes

src/content/docs/troubleshooting.mdx
Updates troubleshooting docs to include the flags required to bypass native/asset change warnings when patching.
This also removes what was supposed to be a custom header slug that was rendering inline:
=> Add flags to native/asset change troubleshooting sections

src/content/docs/flutter-version.mdx
I moved our "min supported" version to 3.22.3 for iOS even though
the tool will actually let your release on 3.22.2 as well.
3.22.3 and 3.22.2 are very similar in code from upstream, but the
3.22.3 from us includes a much improved linker.
=> docs: update our version docs for 3.22.3

src/content/docs/faq.mdx, src/content/docs/status.mdx
Also updated status page now that iOS works well for most users.
=> docs: Update FAQ that we have no current plans to support on-prem

src/content/docs/ci/fastlane.mdx
Our new version of the fastlane plugin autodetects the ipa path, so it is no longer necessary to explicitly pass this value.
=> Update fastlane guide to reflect plugin update

src/content/docs/status.mdx
"For now, can help" -> "For now, we can help"
=> Fix typo on status page

src/content/docs/ci/_authentication.mdx, src/content/docs/ci/codemagic.mdx
**READY**
Updates the Codemagic guide to include walkthroughs for releasing, patching, and publishing both iOS and Android.
=> Refresh Codemagic guide

src/content/docs/guides/hybrid-apps/android.mdx
**READY**
Update guide to include `packaging.jniLibs.keepDebugSymbols.add("**/libapp.so")` to prevent hash mismatches when using `compileSdk 34`.
Fixes https://github.com/shorebirdtech/shorebird/issues/2369
=> fix: update hybrid android guide to fix hash mismatch issue

src/content/docs/guides/flavors/android.mdx, src/content/docs/guides/flavors/ios.mdx
Adding a note explaining that the parameters to `shorebird preview` shown in our flavors docs are optional to address confusion like https://github.com/shorebirdtech/shorebird/issues/2549#issuecomment-2433464261
=> Add note explaining preview params are optional

src/content/docs/guides/staging-patches.mdx
**READY**
In older shorebird versions, we stage a patch by doing:
```sh
shorebird patch android --staging
shorebird patch ios --staging
```
Currently, --staging flag is deprecated and the updated way to stage a patch is by doing:
```sh
shorebird patch android --track=staging
shorebird patch ios --track=staging
```
This PR aims to update the doc reflecting this change.
=> update patch docs to reflect track

src/content/docs/billing.mdx
=> Tweak language on billing page

src/content/docs/code-push/release.mdx, src/content/docs/code-push/rollback.mdx
I didn't find us documenting this anywhere, so I wrote some docs.
Not sure if this is the best place, but we can always move it later.
=> docs: add a section on automatic rollback

src/content/docs/code-push/release.mdx, src/content/docs/troubleshooting.mdx
Adds a section to our iOS releasing docs explaining how to use export options plist files. This is in response to the recent uptick in support questions about this topic.
=> Add section about export options plist

src/content/docs/code-push/patch.mdx, src/content/docs/code-push/release.mdx, src/content/docs/index.mdx
=> docs: add windows

src/content/docs/troubleshooting.mdx
We used to have one in /status, i've now created a modern one in /troubleshooting.
=> feat: add a doc about link warnings

src/content/docs/guides/crash-reporting/Integrations/crashlytics.mdx, src/content/docs/guides/crash-reporting/Integrations/sentry.mdx, src/content/docs/update-strategies.mdx
Hi! Just happened to notice deprecated methods in your docs.
**READY**
The Crashlytics and Sentry Integration pages contained outdated methods that have been replaced in the shorebird_code_push plugin v2.0.0-dev.1. 
I've also replaced a dead link on the Update Strategies page that pointed to the same method, which no longer exists.
=> Replaces ShorebirdCodePush in favor of ShorebirdUpdater

src/content/docs/code-push/overview.mdx
**READY**
There was some confusion around `.arb` files and if they could be updated using Shorebird. Given that `.arb` files are assets we can understand the confusion but need to remember that these files are not actually included in the application bundle and are instead used to generate Dart code. Therefore this falls under the "Generated code" item we have in the docs already.
Adding a note that will point to the Flutter Internationalization documentation to help solve this confusion.
=> fix: Add link explaining string asset support as generated code

src/content/docs/system/security.mdx
**READY**
Corresponds with the update to the handbook page https://github.com/shorebirdtech/handbook/pull/50
This update makes this page more focused on the service and products we provide and the security practices behind them. Attempted to reorganize the page as well.
=> feat: organize security page to be system and product focused

src/content/docs/system/security.mdx
**READY**
Called out in the review for https://github.com/shorebirdtech/handbook/pull/50. This section was duplicated between docs and handbook. Its more company overarching so removing it from docs.
=> fix: removing duplicate section from security page

astro.config.mjs
**READY**
I think this was a copy/pasta error from when I did the update on handbook
=> fix: fix github url

astro.config.mjs, package-lock.json, package.json
**READY**
Integration of the `starlight-image-zoom` library to enable image zoom on click.
Closes https://github.com/shorebirdtech/docs/issues/240.
=> feat: add support for image zoom

src/content/docs/code-push/patch.mdx
**READY**
Adding in some language specifically stating the `--release-version latest` flag for patches.
=> fix: add statement on release-version latest

src/content/docs/code-push/update-strategies.mdx
**READY**
Some incorrect markdown headings were making the page look weird.
=> fix: update headings on update strategies

src/content/docs/code-push/guides/hybrid-apps/ios.mdx
Our docs were not especially clear that this is the only method of add-to-app that we support.
=> Add note about using iOS Frameworks for iOS add-to-app
