shorebirdtech/docs

docusaurus.config.js, static/CNAME
**READY**
- chore: update CNAME
=> chore: update CNAME

docusaurus.config.js
**READY**
- chore: respect system color scheme
=> chore: respect system color scheme

docs/index.md
**READY**
- docs: add account upgrade to getting started
=> docs: add account upgrade to getting started

docs/index.md
=> docs: add windows install instructions

docs/architecture.md, docs/faq.md, docs/status.md, docs/uninstall.md, package-lock.json, package.json
I'm not sure we actually need all of these.  I did modify them
some to make more sense.  But I suspect we will need another pass
to clean these up.
=> docs: add more docs from shorebird repo

docs/index.md
Add a section to getting started about our Discord.
=> docs: Add a section about Discord

docs/index.md
Fixes https://github.com/shorebirdtech/shorebird/issues/394
=> fix: update windows install command to address https://github.com/shorebirdtech/shorebird/issues/394

docs/code_push/release.md
Adds docs for `shorebird releases list` and `shorebird releases delete`.
Fixes https://github.com/shorebirdtech/shorebird/issues/407
=> docs: add 'Manage Releases' section

docs/code_push/build.md, docs/code_push/initialize.md, docs/code_push/patch.md, docs/code_push/release.md, docs/code_push/run.md
**READY**
- docs: include `--flavor` and `--target` options
=> docs: include `--flavor` and `--target` options

docs/index.md
Nothing changes, just provide alternative install command on ubuntu, in case the first install command failed.
- [ x ] 📝 Documentation
=> docs: add alternative install command, if the first one failed.

docs/faq.md, docs/status.md
More feedback from customers.  Also link to more issues.
=> docs: Update faq and status with more customer questions.

docs/faq.md, docs/status.md
Add an FAQ discussing channel alternatives.
=> docs: Add an FAQ discussing channel alternatives.

docs/guides/multiple_deployment_tracks.md
**READY**
- docs: add guide for multiple deployment tracks
=> docs: add guide for multiple deployment tracks

docs/guides/multiple_deployment_tracks.md
**READY**
- chore(multiple_deployments): use caution admonition
=> chore(multiple_deployments): use caution admonition

Dockerfile, docker-compose.yaml
**READY**
- fix: `docker compose up --build`
=> fix: `docker compose up --build`

docs/code_push/patch.md, docs/code_push/release.md
**READY**
- docs: adjust release and patch output
=> docs: adjust release and patch output

docs/faq.md
New questions from Discord this morning:
```
1. Where are resources saved? Does it affect Shorebird's performance when there is an Internet problem?
2. Does Shorebird limit the Android version? (The oldest version can be used)
```
=> docs: Add more FAQs from Discord this morning.

docs/code_push/release.md, docs/guides/code_push_release.md, docs/guides/multiple_deployment_tracks.md
**READY**
- docs: adjust to use `shorebird release android`
=> docs: adjust to use `shorebird release android`

docs/code_push/patch.md, docs/faq.md, docs/guides/code_push_release.md, docs/guides/multiple_deployment_tracks.md
**READY**
- docs: update `shorebird patch` usage
=> docs: update `shorebird patch` usage

docs/index.md, docs/status.md
Also added a note to the getting started doc about that everything
is done via the `shorebird` command line.
=> docs: Add a note about iOS status to our docs.

docs/faq.md
Add more answers to questions I got via email
=> docs: Add more answers to questions I got via email

docs/ci/_category_.json, docs/ci/github.md, package-lock.json, package.json
**READY**
- docs(ci): add GitHub CI docs (closes https://github.com/shorebirdtech/shorebird/issues/558)
=> docs(ci): add GitHub CI docs

docs/faq.md
This has come up in a few customer calls.
=> docs: Add FAQ about availability of Shorebird within countries

docs/guides/code_push_quickstart.md, docs/status.md
**READY**
- docs: minor status and pricing updates
=> docs: minor status and pricing updates

docs/guides/code_push_add_to_app.md, docs/guides/code_push_quickstart.md, docs/guides/multiple_deployment_tracks.md, docs/index.md
**READY**
- docs: remove `shorebird account subscribe`
=> docs: remove `shorebird account subscribe`

docs/faq.md
Adding another question from discord and updating other entries.
=> docs: Update FAQ with questions from Discord

docs/guides/code_push_quickstart.md
**READY**
- fix(quickstart): update release and patch commands
=> fix(quickstart): update release and patch commands

docs/index.mdx, docusaurus.config.js
**READY**
Adds Mac/Linux + Windows tabs, updates windows install instructions to address https://github.com/shorebirdtech/shorebird/issues/736.
Fixes https://github.com/shorebirdtech/shorebird/issues/736
=> Update windows install instructions to include required permissions

docs/code_push/release.md, docs/guides/multiple_deployment_tracks.md
**READY**
- fix(multiple_deployments): update release and patch commands
=> fix(release): update release command usage

docs/index.mdx
**READY**
- docs: update landing page to include the shorebird console
=> docs: update landing page to include the shorebird console

docs/status.md
**READY**
- docs: update status to reflect the current status
=> docs: update status to reflect the current status

docs/ci/github.md
**READY**
- docs: update github pre-requisites
=> docs: update github pre-requisites

docs/troubleshooting.md
**READY**
Adds troubleshooting instructions for a couple common "I created a patch but it's not applying" issues.
Part of https://github.com/shorebirdtech/docs/issues/71
=> Add extra troubleshooting instructions to address patches not applying

docs/faq.md
**READY**
Clarifies which types of changes we support and do not support.
Part of https://github.com/shorebirdtech/docs/issues/71
=> docs: add types of changes supported to FAQ

docs/guides/code_push_quickstart.md
**READY**
We have a free tier, subscribing is no longer required.
=> Remove 'and subscribed' from quickstart

docs/code_push/release.md
**READY**
- docs(release): improve `shorebird release` docs
=> docs(release): improve `shorebird release` docs

docs/guides/code_push_quickstart.md
**READY**
- docs: adjust quickstart to reference console.shorebird.dev
=> docs: adjust quickstart to reference console.shorebird.dev

docs/guides/code_push_quickstart.mdx
=> Add ios alpha to code push quickstart

docs/concepts.md, docs/faq.md, docs/status.md
Still need more work here, but this is probably good enough to land as is.
=> docs: document iOS Alpha status

docs/code_push/preview.md
=> Add iOS to preview docs

docs/ci/codemagic.mdx
As requested in https://github.com/shorebirdtech/docs/pull/94
=> Fix: Paths in codemagic instructions are wrong on linux.

docs/guides/code_push_release_app_store.md
**READY**
- docs: fix ios status link
=> docs: fix ios status link

docs/guides/add_to_app/android.md, docs/guides/add_to_app/ios.md, docs/guides/multiple_deployment_tracks/_category_.json, docs/guides/multiple_deployment_tracks/android.md, docs/guides/release/android.md, docs/guides/release/ios.md
**READY**
- docs: adjust sidebar labels for guides
=> docs: adjust sidebar labels for guides

docs/troubleshooting.md
**READY**
The `--` issue is with Powershell, not the `args` package. This updates the troubleshooting docs to clarify.
=> Update troubleshooting to clarify the -- issue is with powershell

docs/ci/codemagic.mdx
**READY**
Demo:
https://github.com/shorebirdtech/docs/assets/24459435/862e0df7-c23c-47fc-adba-38bf2a4b24c5
Successful build on Windows:
Closes #98
=> docs: add windows tab for using Shorebird on Codemagic Windows machines

docs/architecture.md, docs/concepts.md, docs/faq.md, docs/flutter-version.md, docs/status.md, docs/troubleshooting.md, docs/uninstall.md
**READY**
- docs(flutter-version): add section on Flutter version management
=> docs(flutter-version): add section on Flutter version management

docs/index.mdx
**READY**
- docs(index): adjust outputs for various commands
=> docs(index): adjust outputs for various commands

docs/flutter-version.md
**READY**
- docs(flutter-version): adjust support matrix
=> docs(flutter-version): adjust support matrix

docs/ci/github.md
**READY**
- docs(ci): include tip regarding specifying the flutter-version
=> docs(ci): include tip regarding specifying the flutter-version

docs/status.md
This is less down-trodden and more confident about what we've delivered.
=> docs: Update our status page

docs/ci/github.md
**READY**
- docs(ci): remove `--release-version` from `shorebird patch`
=> docs(ci): remove `--release-version` from `shorebird patch`

docs/faq.md
add an FAQ about shorebird seeing source code.
=> docs: add an FAQ about shorebird seeing source code.

docs/update_strategies.md
This comes from frequent questions in the Discord. I'm sure
there is more we can do here.
Fixes https://github.com/shorebirdtech/shorebird/issues/1130
Fixes https://github.com/shorebirdtech/shorebird/issues/1123
=> docs: Write a guide on update strategies

docs/guides/add-to-app/android.md
READY
Typo: Changed `nubmer` to `number`
=> Update android.md: Typo: Changed `nubmer` to `number`

docs/ci/codemagic.mdx
FYI @mikhail-tokarev @nilsreichardt
=> docs: add link to codemagic blog

docs/status.md
Fixes https://github.com/shorebirdtech/shorebird/issues/679
=> docs: iOS supports warning about non-dart changes

docs/code_push/release.mdx
Fixes https://github.com/shorebirdtech/shorebird/issues/1178
I suspect we could write more (I initially started this as a separate
doc, but didn't have enough to say to bother splitting).
=> docs: Add explicit mention of using Shorebird in a sideloaded env.

docs/faq.md, docs/teams.md
Fixes https://github.com/shorebirdtech/shorebird/issues/1222
=>     docs: Add a doc on collaborators / teams

docs/teams.md
For https://github.com/shorebirdtech/shorebird/issues/1225
=> docs: Document how to transfer an app

docs/flutter-version.md
**READY**
- docs: update supported Flutter versions
=> docs: update supported Flutter versions

docs/guides/flavors/android.md
=> fix: unindent info callout close tag

docs/guides/flavors/android.md, docs/guides/flavors/ios.md
**READY**
Adds docs explaining how to add new flavors to an existing shorebird app for iOS and Android.
Fixes https://github.com/shorebirdtech/docs/issues/137
=> Document adding new flavors

docs/flutter-version.md
**READY**
- chore(flutter_version): add 3.13.5
=> chore(flutter_version): add 3.13.5

docs/troubleshooting.md
**READY**
Part of https://github.com/shorebirdtech/shorebird/issues/1286. https://github.com/shorebirdtech/shorebird/issues/1286 will be closed once we add a link to this in the CLI.
=> Add troubleshooting section about native change warnings

docs/guides/release/ios.md
Xcode 15 adds an extra dialog step, update the docs to reflect.
=> Update iOS release docs for Xcode 15

docs/flutter-version.md
**READY**
- docs(flutter-version): add Flutter 3.13.6
=> docs(flutter-version): add Flutter 3.13.6

docs/ci/_category_.json, docs/concepts.md, docs/guides/flavors/_category_.json, docs/guides/hybrid-app/_category_.json, docs/guides/staging-patches.md, docs/status.md, docs/update-strategies.md
**READY**
- docs: add `staging-patches` guide (closes #164)
=> docs: add `staging-patches` guide

docs/troubleshooting.md
Fixes https://github.com/shorebirdtech/docs/issues/162
=> doc: add a section to troubleshooting about asset changes

docs/troubleshooting.md
Describes remedies for https://github.com/shorebirdtech/shorebird/issues/1431.
Fixes https://github.com/shorebirdtech/shorebird/issues/1431.
=> Add troubleshooting section for invalid podfile message

docs/ci/github.md
**READY**
- docs(github): add `shorebird-release` action
=> docs(github): add `shorebird-release` action

docs/uninstall.md
Updates uninstall/unsubscribe instructions to point to the console.
=> Update uninstall instructions

docs/architecture.md
=> docs: update our architecture docs to say more

docs/faq.md
See [this Discord thread](https://discord.com/channels/1030243211995791380/1204451421748072478)
=> Add FAQ about dart define support

docs/faq.md, docs/update-strategies.md
Tightens up the Update Strategies section for clarity.
=> Condense update strategies doc

docs/status.md
Removed spurious link, other small updates.
=> docs: Update status.md

docs/status.md
Indicated iOS is now beta status
**READY**
Update in `docs/status.md` to indicate iOS is now beta status
=> Update in `docs/status.md` to indicate iOS is now beta status

docs/status.md
Clean up our status page in preperation for 1.0.
=> docs: update status page to discuss link percentage

docs/ci/codemagic.mdx
=> docs: ios configuration changes needed for codemagic

docs/troubleshooting.md
From https://discord.com/channels/1030243211995791380/1224384748412080159
=> Add troubleshooting note about old Xcode versions

docs/code_push/patch.mdx
**READY**
- chore(patch): remove reference to iOS beta (closes https://github.com/shorebirdtech/shorebird/issues/1880)
=> chore(patch): remove reference to iOS beta

docs/troubleshooting.md
Fix wrongly formatted markdown link display.
**READY**
Update in `troubleshooting.md` to fix link display
=> Update in `troubleshooting.md` to fix link display

docs/ci/_ci_authentication.md
This reverts commit e54ffd2a4315fcfa534164a2aeb3dba84e8c7f0c.
**READY**
=> revert "docs: Adding explanation on docs about getting the ci token on the console (#206)"

docs/ci/github.mdx
**READY**
Update the docs to use the new `shorebird-patch` GHA
=> docs: Update github CI docs to use the new action

.github/cspell.json, .github/workflows/main.yaml, docs/faq.md, docs/guides/hybrid-app/android.md, docs/guides/hybrid-app/ios.md, docs/guides/release/android.md, docs/guides/release/ios.md, docs/index.mdx, docs/teams.md
**READY**
Adds cspell action to ensure the docs have no typos
=> feat: adding cspell ci checking

docs/overview.md
Make explicit that dependencies are dart dependencies.  Fixes https://github.com/shorebirdtech/shorebird/issues/1879.
=> docs: Update overview.md

docs/guides/release/ios.md
=> docs: Update ios.md

docs/troubleshooting.md
**READY**
Just a typo in troubleshooting section
=> fix(typo): Update troubleshooting.md

docs/troubleshooting.md
**READY**
Adds answers to "what happens if I ignore a native/asset change warning while patching?"
=> Explain consequences of ignoring unpatchable change warnings

astro.config.mjs, package-lock.json, package.json, plugins/rehype-autolink.ts, src/components/starlight/MarkdownContent.astro
**READY**
- feat: add automatic header anchor links
=> feat: add automatic header anchor links

src/content/docs/architecture.mdx
**READY**
- docs: minor adjustments to the architecture section
=> docs: minor adjustments to the architecture section

src/content/docs/faq.mdx
**READY**
Adds a item at our docs FAQ about account deletion.
=> docs: adding FAQ item about account deletion

astro.config.mjs, src/content/docs/architecture.mdx, src/content/docs/ci/codemagic.mdx, src/content/docs/ci/generic.mdx, src/content/docs/ci/github.mdx, tailwind.config.mjs
This has come up several times on Discord.
=> docs: add new Generic CI instructions

src/content/docs/flutter-version.mdx
**READY**
- docs: adjust minimum flutter version for iOS
=> docs: adjust minimum flutter version for iOS

astro.config.mjs, src/content/docs/guides/fastlane.mdx
**Ready**
Adds guide describing how to use https://github.com/shorebirdtech/fastlane-plugin-shorebird
Fixes https://github.com/shorebirdtech/docs/issues/233
=> Add fastlane guide

.github/cspell.json, src/content/docs/troubleshooting.mdx
**READY**
Adds a section in our trouble shooting section about the `Unsupported Class File Major version`
This PR is part of the effort to solve https://github.com/shorebirdtech/shorebird/issues/1821.
In a follow up PR, I plan on using the link to this doc in the CLI, where it will check if an error is the one this docs refers to, and will link to this section.
=> docs: adding trouble shooting about Unsupported class error

src/content/docs/index.mdx
**READY**
Adding some docs on how to install Shorebird manually by cloning the repository.
Enabling users to install it in any folder they prefer.
Fix https://github.com/shorebirdtech/shorebird/issues/2140
=> docs: adding instructions on how to manual install shorebird

src/content/docs/guides/release/ios.mdx
Fixes https://github.com/shorebirdtech/docs/issues/223
=> add exportOptions.plist info to iOS releasing page

src/content/docs/troubleshooting.mdx
Relevant discord thread: https://discord.com/channels/1030243211995791380/1257319863471575081
=> Add note about Xcode auto-incrementing build numbers

src/content/docs/code-push/initialize.mdx
**READY**
- docs: add note about `--display-name` to `shorebird init`
=> docs: add note about `--display-name` to `shorebird init`

package-lock.json
**READY**
- chore: `npm audit`
=> chore: `npm audit`

package-lock.json, src/content/docs/teams.mdx
Covers the common case of "CEO buys shorebird, wants CTO to set up apps"
=> docs: add an FAQ to the Teams docs

astro.config.mjs
This updates the sidebar to match the page title.
=> Update patch signing sidebar title from "preview" to "beta"

astro.config.mjs, src/components/RemoteCode.astro, src/components/guides/development-workflow/CICheckSnippet.astro, src/content/docs/guides/development-workflow.mdx
**READY**
- docs: add "Development Workflow" documentation
=> docs: add "Development Workflow" documentation

astro.config.mjs, src/components/starlight/Head.astro
**READY**
- feat: add plausible analytics
=> feat: add plausible analytics

src/content/docs/orgs.mdx
**READY**
- docs(orgs): adjustments to collaborator roles
=> docs(orgs): adjustments to collaborator roles

src/content/docs/ci/github.mdx
**READY**
- docs(github): include cache input in setup-shorebird action
=> docs(github): include cache input in setup-shorebird action

.github/cspell.json, astro.config.mjs, src/content/docs/guides/percentage-based-rollouts.mdx
Adds https://docs.google.com/document/d/1MHBuO3Dpsqlf5mjsw7dVwQeNLzIyVlnJAJ1CH6evM3I/edit?tab=t.0#heading=h.dbps5k4315bq as a guide
=> Add guide for percentage-based rollouts

src/content/docs/guides/percentage-based-rollouts.mdx
**READY**
- docs(progressive_rollout): adjust snippets to align with sample app
=> docs(progressive_rollout): adjust snippets to align with sample app

astro.config.mjs, src/content/docs/billing.mdx, src/content/docs/guides/staging-patches.mdx
Eventually we should pull in content from https://shorebird.dev/blog/simplified-pricing/
=> docs: Add a page on billing.

src/content/docs/faq.mdx
We've gotten this question a few times, figure it should go in the FAQ.
=> docs: do I still need to submit to the stores?

src/content/docs/index.mdx
**READY**
- chore: adjust getting started snippet diff
=> chore: adjust getting started snippet diff

src/content/docs/index.mdx
**READY**
- docs(getting_started): include `shorebird login` step
=> docs(getting_started): include `shorebird login` step

src/content/docs/flutter-version.mdx
READY
Use a different Flutter Versions --> Use a different Flutter Version
=> docs: fix typo in 'Flutter Version' section

package-lock.json, package.json
**READY**
- chore(deps): upgrade to astro v5
=> chore(deps): upgrade to astro v5

src/content/docs/index.mdx
**READY**
It wasn't clear what "preview" meant here, so I updated the language a bit.
=> Clarify that shorebird preview runs the app

.github/cspell.json, src/content/docs/code-push/preview.mdx
Adds instructions re: previewing hybrid apps.
Fixes https://github.com/shorebirdtech/shorebird/issues/2816
=> Add hybrid app preview instructions

src/content/docs/code-push/patch.mdx, src/content/docs/code-push/release.mdx, src/content/docs/index.mdx
=> docs: add Linux

src/content/docs/code-push/patch.mdx, src/content/docs/code-push/release.mdx, src/content/docs/index.mdx
**READY**
- chore: remove beta from desktop platforms
=> chore: remove beta from desktop

src/content/docs/guides/patch-signing.mdx
**READY**
- docs: remove beta from patch signing docs
=> docs: remove beta from patch signing docs

src/content/docs/flutter-version.mdx
**READY**
- docs(flutter-version): include linux
=> docs(flutter-version): include linux

src/content/docs/code-push/overview.mdx
**READY**
Missed this in #345 🤦
=> fix: add missed parentheses

src/content/docs/Code Push/Continuous Integration/_authentication.mdx, src/content/docs/Code Push/Continuous Integration/fastlane.mdx, src/content/docs/Code Push/Continuous Integration/github.mdx, src/content/docs/Code Push/Guides/Flavors/android.mdx, src/content/docs/Code Push/Guides/Flavors/ios.mdx, src/content/docs/Code Push/Guides/Hybrid Apps/android.mdx, src/content/docs/Code Push/Guides/Hybrid Apps/ios.mdx, src/content/docs/Code Push/Guides/Submitting/app-store.mdx, src/content/docs/Code Push/Guides/Submitting/play-store.mdx, src/content/docs/Code Push/Guides/development-workflow.mdx, src/content/docs/Code Push/Guides/patch-signing.mdx, src/content/docs/Code Push/Guides/staging-patches.mdx, src/content/docs/Code Push/Guides/white-labeling.mdx, src/content/docs/Code Push/initialize.mdx, src/content/docs/Code Push/overview.mdx, src/content/docs/Code Push/patch.mdx, src/content/docs/Code Push/preview.mdx, src/content/docs/Code Push/release.mdx, src/content/docs/Code Push/rollback.mdx, src/content/docs/Code Push/system-architecture.mdx, src/content/docs/Code Push/update-strategies.mdx, src/content/docs/Getting Started/flutter-version.mdx, src/content/docs/Getting Started/quick-start.mdx, src/content/docs/faq.mdx
**READY**
Fixing the formatting that the Prettier changes screwed up. Needed some extra spacing so it doesn't clobber callouts.
=> fix: get the callouts working again

src/content/docs/code-push/guides/development-workflow.mdx, src/content/docs/code-push/guides/staging-patches.mdx
**READY**
- docs: update staging usage to `--track=staging`
=> docs: update staging usage to `--track=staging`

src/content/docs/code-push/guides/staging-patches.mdx
**READY**
- fix(staging-patches): `shorebird preview` snippet
=> fix(staging-patches): `shorebird preview` snippet

src/content/docs/code-push/guides/testing-patches.mdx
Part of https://github.com/shorebirdtech/updater/issues/255
=> Adjust "testing patches" to remove reference to fixed tracks

src/content/docs/code-push/create.mdx, src/content/docs/code-push/initialize.mdx, src/content/docs/code-push/patch.mdx, src/content/docs/code-push/performance.mdx, src/content/docs/code-push/preview.mdx, src/content/docs/code-push/release.mdx, src/content/docs/code-push/rollback.mdx, src/content/docs/code-push/uninstall.mdx, src/content/docs/code-push/update-strategies.mdx
**READY**
- feat: add `shorebird create` page to docs
=> feat: add `shorebird create` page to docs

src/content/docs/getting-started/flutter-version.mdx
Updates the minimum required windows version to reflect https://github.com/shorebirdtech/shorebird/commit/3b9888ea50fd59c59a514cb195590c373f130ee9
=> Update minimum windows version

src/content/docs/faq.mdx
**READY**
- docs(faqs): fix bad link
=> docs(faqs): fix bad link

src/content/docs/code-push/system-architecture.mdx
**READY**
Reimplementation of #333. Easier to do this then merge main in since so many changes in structure since then.
=> feat: adding doc explaining how code push works

src/content/docs/getting-started/flutter-version.mdx
**READY**
Attempting to get ahead of any future questions as people upgrade to 3.35.x
=> fix: add note on 3.35 support

src/content/docs/getting-started/flutter-version.mdx
Missed a date in the previous flutter note. Also updating the Flutter version example.
=> fix: add date for previous flutter note

src/content/docs/code-push/faq.mdx
=> fix: typo in billing period reset explanation

src/content/docs/ci/checks/check-spelling.mdx
**READY**
Original link was getting a 404.
=> fix: CSpell link in Check Spelling documentation
